tap "codefresh-io/cli"
tap "coursier/formulas"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "int128/kubelogin"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Kubernetes command-line interface
brew "kubernetes-cli"
# Kubernetes prompt info for bash and zsh
brew "kube-ps1"
# Tool that can switch between kubectl contexts easily and create aliases
brew "kubectx"
# Apache Kafka C/C++ library
brew "librdkafka"
# Mac App Store command-line interface
brew "mas"
# Manage multiple Node.js versions
brew "nvm"
# Development kit for the Java programming language
brew "openjdk"
# Cryptography and SSL/TLS Toolkit
brew "openssl@3"
# Object-relational database system
brew "postgresql"
# Python version management
brew "pyenv"
# Powerful, clean, object-oriented scripting language
brew "ruby"
# Rust toolchain installer
brew "rustup-init"
# Build tool for Scala projects
brew "sbt"
# Fish-like fast/unobtrusive autosuggestions for zsh
brew "zsh-autosuggestions"
# Codefresh CLI provides a full and flexible interface to interact with Codefresh.
brew "codefresh-io/cli/codefresh"
# Launcher for Coursier
brew "coursier/formulas/coursier"
# A kubectl plugin for Kubernetes OpenID Connect authentication
brew "int128/kubelogin/kubelogin"
# Web browser focusing on privacy
cask "brave-browser"
# Universal database tool and SQL client
cask "dbeaver-community"
# App to build and share containerized applications and microservices
cask "docker"
# Web browser
cask "firefox"
# Web browser
cask "google-chrome"
# IDE for Java development - community edition
cask "intellij-idea-ce"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# Kubernetes IDE
cask "lens"
# Meet, chat, call, and collaborate in just one place
cask "microsoft-teams"
# Explore and manipulate your MongoDB data
cask "mongodb-compass"
# App to write, plan, collaborate, and get organized
cask "notion"
# Collaboration platform for API development
cask "postman"
# IDE for Python programming - Community Edition
cask "pycharm-ce"
# Move and resize windows using keyboard shortcuts or snap areas
cask "rectangle"
# Team communication and collaboration software
cask "slack"
# Music streaming service
cask "spotify"
# JDK from the Eclipse Foundation (Adoptium)
cask "temurin11"
# JDK from the Eclipse Foundation (Adoptium)
cask "temurin8"
# Customizable email client
cask "thunderbird"
# Open-source code editor
cask "visual-studio-code"
# Multimedia player
cask "vlc"
# Video communication and virtual meeting platform
cask "zoom"
